# Generated by Django 4.1.5 on 2023-01-11 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raça',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raça', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='pets')),
                ('nome', models.CharField(max_length=300)),
                ('descrição', models.TextField()),
                ('estado', models.CharField(max_length=164)),
                ('cidade', models.CharField(max_length=164)),
                ('telefone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], max_length=1)),
                ('raça', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='divulgation.raça')),
                ('tags', models.ManyToManyField(to='divulgation.tag')),
                ('usuário', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
