# Generated by Django 4.1.5 on 2023-01-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
