# Generated by Django 4.1.5 on 2023-01-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgation', '0002_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raça',
            name='raça',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
