# Generated by Django 4.1.5 on 2023-01-12 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgation', '0003_alter_raça_raça'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='raça',
            new_name='raça_id',
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(upload_to='pets', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'webp'])]),
        ),
    ]
