# Generated by Django 4.1.5 on 2023-01-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgation', '0004_rename_raça_pet_raça_id_alter_pet_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='raça_id',
            new_name='raça',
        ),
    ]
