# Generated by Django 4.1.5 on 2023-01-14 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoçõespedido',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
